name: picto_widget
description: Create great apps with Pictograms using OTTAA Picto widget, we feature a minimalistic design to foster understanding.
version: 0.0.5+3
homepage: https://github.com/OTTAA-Project/PictoWidget

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: